# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  MATHWORKS_LICENSING_ENDPOINT: stage
  
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        release: [R2021a, R2021b, R2022a, R2022b]
        
    # The type of runner that the job will run on
    runs-on: ${{matrix.platform}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Store $HOME
        run: echo "GH_HOME=$HOME" >> $GITHUB_ENV
        
      - name: Cache Support Packages
        id: cache-sp
        uses: actions/cache@v3
        with:
          path: ${{ env.GH_HOME }}/Documents/MATLAB
          key: matlab-sp-${{ matrix.platform }}-${{ matrix.release }}

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-rc0
        with: 
          release: ${{matrix.release}}
          cache: true
          products: |
            Statistics_and_Machine_Learning_Toolbox
            Simulink
            Simulink_Test
            Simulink_Check
            CI/CD_Automation_for_Simulink_Check

      - name: Look inside $HOME
        run: ls $HOME

      # Runs a set of commands using the runners shell
      - name: Check MATLAB Install
        uses: matlab-actions/run-command@v2-rc0
        with:
          command: ver, which('runprocess'), disp(getenv('HOME'))
          
      # Runs a set of commands using the runners shell
      - name: Run all tests
        uses: matlab-actions/run-tests@v2-rc0
        with:
          source-folder: metapop_code
          use-parallel: true
          
          
